### ISSUE TITLE
"python manage.py syncdb --noinput" migration error

### ISSUE THREAD

**Issue by oden08** [vrchost/rooibos#10]
At the step of running "python manage.py syncdb --noinput" I get the following:

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration django_celery_results.0003_auto_20181106_1101 dependencies reference nonexistent parent node (u'celery_results', u'0002_add_task_name_args_kwargs')

**I have ran it multiple times (as suggested in the documentation) but still get the same error.  Any ideas?

**Comment by knabar** [comment]
Does `django-admin migrate --noinput`, or specifically `django-admin migrate django_celery_results --noinput`, work?

The `syncdb` command should not be used anymore, I'll have to change that in the documentation.

**Comment by oden08** [comment]
Thank you for messaging me back.  I am getting the following running django-admin (same error):

>>
(venv) [mdid@mdid3 rooibos]$ django-admin migrate django_celery_results --noinput
System check identified some issues:

WARNINGS:
data.Field.equivalent: (fields.W340) null has no effect on ManyToManyField.
userprofile.UserProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Traceback (most recent call last):
  File "/opt/mdid/venv/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/opt/mdid/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration django_celery_results.0003_auto_20181106_1101 dependencies reference nonexistent parent node (u'celery_results', u'0002_add_task_name_args_kwargs')
<<

**Comment by knabar** [comment]
Ok, I believe the issue is with a version of `django_celery_results` that is broken.

Please try
```
pip install django-celery-results==1.0.4
```
and run the migrations again.

Alternatively you should be able to downgrade by running
```
django-admin migrate django_celery_results 0001 --noinput
pip install django-celery-results==1.0.1
```
