### ISSUE TITLE
invalid html in metadata causes 500 error

### ISSUE THREAD

**Issue by hanleybrand** [vrchost/rooibos#12]
This isn't a real show stopper, but an annoyance - HTML tags in a field can cause the pdf generator to throw an error and fail to generate a pdf (```paraparser: syntax error: invalid attribute name rel attrMap=['backColor', 'backcolor', 'bgcolor', 'color', 'fg', 'fontName', 'fontSize', 'fontname', 'fontsize', 'href', 'name', 'textColor', 'textcolor']```)

The record can be edited to remove the tags, but I'll see if I can figure out a fix and submit a pull request for the next version.

Here's an example of what breaks it - it's the ```rel="nofollow"``` attribute in this case:

```html
<para>
<b>Title</b>: Brancusi, The Kiss, 1916<br />
<b>Description</b>: Constantin Brancusi, The Kiss, 1916, limestone, 58.4 x 33.7 x 25.4 cm (Philadelphia Museum of Art) 
<a href="http://smarthistory.org/constantin-brancusi-the-kiss/" rel="nofollow">Learn More on Smarthistory</a><br />
<b>Date</b>: 2014-02-27 00:57:17<br /><b>Identifier</b>: 19434583879<br /><b>Contributor</b>: profzucker<br />
<b>Contributor</b>: Steven Zucker<br />
<b>Subject</b>: brancusi<br />
...
<b>Subject</b>: embrace<br />
<b>Subject</b>: brancusikiss<br />
<b>Source</b>: https://www.flickr.com/photos/profzucker/19434583879/<br /></para>
```
Here's a sample traceback

```
[                django.request]   ERROR 2018-12-03 10:04:57,722 1687 Internal Server Error: /viewers/printviewviewer/5596/ [base.py:256]
Traceback (most recent call last):
  File "/opt/venv/mdid32/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/gallery/rooibos/viewers/views.py", line 24, in viewer_shell
    response = viewer.view(request)
  File "/opt/gallery/rooibos/presentation/viewers.py", line 317, in view
    p = Paragraph(''.join(text), styles['Normal'])
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paragraph.py", line 1151, in __init__
    self._setup(text, style, bulletText or getattr(style,'bulletText',None), frags, cleanBlockQuotedText)
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paragraph.py", line 1173, in _setup
    style, frags, bulletTextFrags = _parser.parse(text,style)
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 1247, in parse
    annotateException('\nparagraph text %s caused exception' % ascii(text))
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/lib/utils.py", line 1390, in annotateException
    rl_reraise(t,v,b)
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 1245, in parse
    self.feed(text)
  File "/usr/lib64/python2.7/HTMLParser.py", line 114, in feed
    self.goahead(0)
  File "/usr/lib64/python2.7/HTMLParser.py", line 158, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib64/python2.7/HTMLParser.py", line 324, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 1268, in handle_starttag
    start(attrs or {})
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 724, in start_a
    A = self.getAttributes(attributes,_anchorAttrMap)
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 1100, in getAttributes
    self._syntax_error('invalid attribute name %s attrMap=%r'% (k,list(sorted(attrMap.keys()))))
  File "/opt/venv/mdid32/lib/python2.7/site-packages/reportlab/platypus/paraparser.py", line 824, in _syntax_error
    raise ValueError('paraparser: syntax error: %s' % message)
ValueError: (u"paraparser: syntax error: invalid attribute name rel attrMap=['backColor', 'backcolor', 'bgcolor', 'color', 'fg', 'fontName', 'fontSize', 'fontname', 'fontsize', 'href', 'name', 'textColor', 'textcolor']", '\nparagraph text u\'<para><b>Title</b>: Brancusi, The Kiss, 1916<br /><b>Description</b>: Constantin Brancusi, The Kiss, 1916, limestone, 58.4 x 33.7 x 25.4 cm (Philadelphia Museum of Art) <a href="http://smarthistory.org/constantin-brancusi-the-kiss/" rel="nofollow">Learn More on Smarthistory</a><br /><b>Date</b>: 2014-02-27 00:57:17<br /><b>Identifier</b>: 19434583879<br /><b>Contributor</b>: profzucker<br /><b>Contributor</b>: Steven Zucker<br /><b>Subject</b>: brancusi<br /><b>Subject</b>: thekiss<br /><b>Subject</b>: philadelphia<br /><b>Subject</b>: sculpture<br /><b>Subject</b>: art<br /><b>Subject</b>: modern<br /><b>Subject</b>: abstraction<br /><b>Subject</b>: cubic<br /><b>Subject</b>: block<br /><b>Subject</b>: couple<br /><b>Subject</b>: embrace<br /><b>Subject</b>: brancusikiss<br /><b>Source</b>: https://www.flickr.com/photos/profzucker/19434583879/<br /></para>\' caused exception')
```

**Comment by hanleybrand** [comment]
In my experience this only happens with flickr imports, but fixing the reportlab generation seems like the better idea since these attributes could come from any source.

**Comment by knabar** [comment]
A number of possible exceptions were already caught when building a reportlab paragraph, I added `ValueException` to the list.  This means that the problematic metadata value does not get added to the PDF, but at least the PDF still gets generated.

**Comment by knabar** [comment]
See https://github.com/vrchost/rooibos/commit/becc1c3449d3c35e68ef1069c51f38bb1900230a

**Comment by hanleybrand** [comment]
Sorry this took me a long time to come back to -  I applied this fix but PrintView just returned blank grey pages instead of the 500 error page.

I ended up fixing it with BeautifulSoup - not a long term fix for sure 😉 

here's the salient snippet:

```python
from BeautifulSoup import BeautifulSoup

# ...

class PrintViewViewer(Viewer):
# ...
    def view(self, request):
# ... at the end of the functions defined

        def clean_for_render(html):
            whitelist = ['backColor', 'backcolor', 'bgcolor',
                         'color', 'fg', 'fontName', 'fontSize',
                         'fontname', 'fontsize', 'href', 'name',
                         'textColor', 'textcolor']
            html.attrs = None
            for e in html.findAll(True):
                for attribute in e.attrs:
                    if attribute[0] not in whitelist:
                        del e[attribute[0]]
            return html
# ... ~line 307
        for index, item in enumerate(items):
            text = []
            values = item.get_fieldvalues(owner=request.user)
            for value in values:
                soup = BeautifulSoup(value.value)
                clean_for_render(soup)
                value.value = soup
                text.append(
                    '<b>%s</b>: %s<br />' % (
                        value.resolved_label, value.value
                    )
                )
```

To test it, I searched for `re="nofollow"` in the explore view and found a disturbing amount of images - I made a presentation with a bunch of them and the PrintView generated surprisingly quickly.

I know that's not the greatest test, but it seems to be much faster than it was, which doesn't really seem to follow but it's bombing out a lot less so    ¯\_(ツ)_/¯


I also threw up my test py file as a gist in case it's helpful:
https://gist.github.com/hanleybrand/8ff082ed536dddb8bb8dca1bc345ccf5

**Comment by knabar** [comment]
Thanks @hanleybrand, I like a whitelist over a growing list of exceptions.  I'll take a closer look after next week.

**Comment by knabar** [comment]
Added a commit to include this fix: https://github.com/vrchost/rooibos/commit/ca6229a0a92cdb9fd0eda18f8087a1e67b385a85
