### ISSUE TITLE
django-admin collectstatic: Apps aren't loaded yet

### ISSUE THREAD

**Issue by adamem1** [vrchost/rooibos#14]
I'm trying to install the latest version of mdid from github on an Ubuntu 16.04 VM, and I think I'm running into a django / celery issue. First, when installing the requirements, I ran into the error: 

> ERROR: django-celery-results 1.1.2 has requirement celery<5.0,>=4.3, but you'll have celery 4.2.1 which is incompatible.

So, I upgraded to celery 4.3 and tried to run django-admin collectstatic. Unfortunately, then I ran into an issue because Django needed to be upgraded as well: 

>  raise ImproperlyConfigured('Celery 4.x requires Django 1.11 or later.

So, I upgraded to Django 1.11, and now when I run "django-admin collectstatic"  I see the following python error: 

```
django-admin collectstatic
Traceback (most recent call last):
  File "/opt/mdid/venv/bin/django-admin", line 10, in <module>
    sys.exit(execute_from_command_line())
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/mdid/rooibos/rooibos/__init__.py", line 5, in <module>
    from .celeryapp import app as celery_app
  File "/opt/mdid/rooibos/rooibos/celeryapp.py", line 6, in <module>
    from rooibos.workers.models import OwnedTaskResult
  File "/opt/mdid/rooibos/rooibos/workers/models.py", line 2, in <module>
    from django.contrib.auth.models import User
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/opt/mdid/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Any advice would be appreciated!

**Comment by knabar** [comment]
I'll need to fix this in `requirements.txt`: `django-celery-results` should be pinned at `1.0.4`.

MDID is not yet compatible with Django 1.9 or higher, so you'll get all sorts of errors if you upgrade Django.

**Comment by adamem1** [comment]
Thanks very much for the fast response. That fixed it for me! I'm really happy this is back under active development!
