### ISSUE TITLE
Calling collectstatic requires a database connection

### ISSUE THREAD

**Issue by pcfens** [vrchost/rooibos#3]
I'm slowly working on packaging MDID up for Docker (hopefully a PR will come in a few days), but I'm running into a few issues that I hope can be resolved without too much trouble.

Calling collectstatic is requiring a database connection, but based on a [fairly old issue](https://code.djangoproject.com/ticket/17656) in django, it looks like that behavior is considered a bug. In this case the database is called because of MDID code and not django itself. Any chance that might be able to be tweaked without breaking anything?

```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/mdid/rooibos/solr/__init__.py", line 10, in <module>
    from rooibos.util.models import OwnedWrapper
  File "/opt/mdid/rooibos/util/models.py", line 28, in <module>
    class OwnedWrapper(models.Model):
  File "/opt/mdid/rooibos/util/models.py", line 39, in OwnedWrapper
    objects = OwnedWrapperManager()
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 144, in inner
    with self:
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'database_server' (0)")
```

**Comment by knabar** [comment]
I'll take a look over the weekend and see if this can be resolved.  I still want to do the necessary work to go to Django 1.9 as well to get rid of all the deprecation warnings - might be some connection there.

**Comment by knabar** [comment]
https://github.com/vrchost/rooibos/commit/f673ce0aad067caba470b06987c1eb8005255062 should resolve this issue; with it I can run `django-admin collectstatic` with an invalid database connection in settings.

**Comment by pcfens** [comment]
Thanks - that seemed to fix everything.

Once I get a chance to test the docker images a little bit more I'll hopefully send another PR along.
